In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a1 = np.array([1,23,34,3,4,122,23,34,534,23,4,34,2,656,85,4,34,5])
print(a1.shape)
a1.reshape(6,3)

(18,)


array([[  1,  23,  34],
       [  3,   4, 122],
       [ 23,  34, 534],
       [ 23,   4,  34],
       [  2, 656,  85],
       [  4,  34,   5]])

In [5]:
b = np.array([1,0,23,34,3,4,122,23,34,999,23,4,34,2,656,85,4,34])

Sort By index

In [6]:
np.argsort(b)

array([ 1,  0, 13,  4,  5, 16, 11,  2,  7, 10, 12,  8,  3, 17, 15,  6, 14,
        9], dtype=int64)

In [7]:
np.argmin(b)

1

In [8]:
np.argmax(b)

9

In [9]:
b = b.reshape(6,3)
b

array([[  1,   0,  23],
       [ 34,   3,   4],
       [122,  23,  34],
       [999,  23,   4],
       [ 34,   2, 656],
       [ 85,   4,  34]])

Sorting Columun indices

In [10]:
np.argsort(b, axis=0)

array([[0, 0, 1],
       [1, 4, 3],
       [4, 1, 0],
       [5, 5, 2],
       [2, 2, 5],
       [3, 3, 4]], dtype=int64)

Sorting Row indices

In [11]:
np.argsort(b, axis=1)

array([[1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [2, 1, 0],
       [1, 0, 2],
       [1, 2, 0]], dtype=int64)