In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],
               [4,5,6]])

Colmun

In [3]:
a.sum(axis=0)

array([5, 7, 9])

Row

In [4]:
a.sum(axis=1)

array([ 6, 15])

In [5]:
b = np.array([[7,8,9],
               [2,8,0]])

In [6]:
np.dot(a, b.transpose())

array([[ 50,  18],
       [122,  48]])

In [7]:
b.transpose()

array([[7, 2],
       [8, 8],
       [9, 0]])

In [8]:
len(dir(np))

618

In [9]:
np.cross(a,b)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [12]:
a = np.array([[11,2,3],
               [4,15,6]])

Sorted on axis "1"

In [13]:
np.sort(a)

array([[ 2,  3, 11],
       [ 4,  6, 15]])

Sorted on axis "0"

In [15]:
np.sort(a, axis=0)

array([[ 4,  2,  3],
       [11, 15,  6]])

We can use Sorting Algorithm

In [19]:
np.sort(a, axis=0, kind="quicksort")

array([[ 4,  2,  3],
       [11, 15,  6]])