## Basic Functions

In [1]:
import numpy as np
array1 = np.array([[3,2,6.5,7,7],[1,12,3,4,5]], dtype ='int32')
print(type(array1))
print(array1)

<class 'numpy.ndarray'>
[[ 3  2  6  7  7]
 [ 1 12  3  4  5]]


In [2]:
array1.shape

(2, 5)

In [3]:
array1.dtype

dtype('int32')

In [4]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones(6).dtype

dtype('float64')

In [6]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
array1

array([[ 3,  2,  6,  7,  7],
       [ 1, 12,  3,  4,  5]])

This is not matrix multiplication

In [8]:
array1*array1

array([[  9,   4,  36,  49,  49],
       [  1, 144,   9,  16,  25]])

In [9]:
12**12

8916100448256

In [10]:
np.array([12**12])


array([8916100448256], dtype=int64)

In [11]:
1/array1

array([[0.33333333, 0.5       , 0.16666667, 0.14285714, 0.14285714],
       [1.        , 0.08333333, 0.33333333, 0.25      , 0.2       ]])

## Slicing

In [12]:
array2 = np.array([5,4,64,3,4,3])

In [13]:
arr = array2[4:6].copy()

In [14]:
arr[0] = 9

In [15]:
array2

array([ 5,  4, 64,  3,  4,  3])

In [16]:
arr

array([9, 3])

In [17]:
array1

array([[ 3,  2,  6,  7,  7],
       [ 1, 12,  3,  4,  5]])

In [22]:
array1[0,3]

7